### ISSUE TITLE
使用虚拟机VMware15.5部署AgileTC docker启动失败

### ISSUE THREAD

**Issue by Reixhp2014** [didi/AgileTC#10]
在虚拟机centos 8.2系统根据docker部署指导安装好环境后，但AgileTC服务启动异常，系统和docker均为初始化安装，其中agile.env 文件和 docker-compose.yml文件也均为文档中的原内容复制，均无自定义配置，服务异常提示如下：
agileTC-caseserver | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
agileTC-caseserver exited with code 1

注：Docker version 19.03.13, build 4484c46d9d

**Comment by gitxiaofeng** [comment]
@yestodayHadRain 你好，docker启动失败的问题你之前使用过程中有碰到吗？对docker这块我们这边暂时还没有深入去调研

**Comment by yestodayHadRain** [comment]
> 
> 
> @yestodayHadRain 你好，docker启动失败的问题你之前使用过程中有碰到吗？对docker这块我们这边暂时还没有深入去调研

这个问题层主在天使群抛出来的时候跟踪过,启动不起来的原因是 caseserver容器和mysql容器 不能互通.初步判断是层主虚拟机网络配置的问题.虚拟机上跑docker容器使用场景比较少,优先级不是太高.层主在win上直接起docker容器是完美启动的.

**Comment by ansonliao** [comment]
The same problem meets, hope can provide the successful `docker-compose.yaml` for reference.
My machine is macOS 11.6.

Thanks.
