### ISSUE TITLE
A person without java experience to deploy service. 

### ISSUE THREAD

**Issue by KimShaotester** [didi/AgileTC#119]
when i use mvn spring-boot:run to start service.

it always report 
2021-09-08 09:46:56.470 [restartedMain][ERROR][com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:933)]:init datasource error,
 url: jdbc:mysql://127.0.0.1:3306/case_manager?**useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8**
java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed

But actually, I already config database as below in application-dev.properties
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/case_manager?**serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true**
spring.datasource.username=root
spring.datasource.password=jc.123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

**Comment by gitxiaofeng** [comment]
> when i use mvn spring-boot:run to start service.
> 
> it always report
> 2021-09-08 09:46:56.470 [restartedMain][ERROR][com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:933)]:init datasource error,
> url: jdbc:mysql://127.0.0.1:3306/case_manager?**useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8**
> java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
> 
> But actually, I already config database as below in application-dev.properties
> spring.datasource.url=jdbc:mysql://127.0.0.1:3306/case_manager?**serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true**
> spring.datasource.username=root
> spring.datasource.password=jc.123456789
> spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

try ”mvn clean package“ ?

**Comment by gitxiaofeng** [comment]
> when i use mvn spring-boot:run to start service.
> 
> it always report 2021-09-08 09:46:56.470 [restartedMain][ERROR][com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:933)]:init datasource error, url: jdbc:mysql://127.0.0.1:3306/case_manager?**useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8** java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
> 
> But actually, I already config database as below in application-dev.properties spring.datasource.url=jdbc:mysql://127.0.0.1:3306/case_manager?**serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true** spring.datasource.username=root spring.datasource.password=jc.123456789 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

or you can try the docker, we've updated it.
