### ISSUE TITLE
编辑器react-agiletc-editor有开源吗？

### ISSUE THREAD

**Issue by logtous** [didi/AgileTC#129]
现在遇到一个需求就是让编辑器可以滚动条控制，而不是通过鼠标滚轮来上下滑动，因为内容特别多的时候用滚轮还是有点不太方便，看了一下接口参数没有找到合适的

**Comment by gitxiaofeng** [comment]
> 现在遇到一个需求就是让编辑器可以滚动条控制，而不是通过鼠标滚轮来上下滑动，因为内容特别多的时候用滚轮还是有点不太方便，看了一下接口参数没有找到合适的

暂时没有。明年会推动这块开源

**Comment by logtous** [comment]
好的 谢谢
