### ISSUE TITLE
用例管理缺少按项目或者模块分组功能，建议增加分组功能

### ISSUE THREAD

**Issue by zhuangjd** [didi/AgileTC#13]
例如有10个模块，每个模块下也有很多功能，分组的话可以，区分各个模块下有多少功能，然后不同用例可以按照分组存放在不同模块下，跟进和执行都比较清晰，目前都是集中在一起管理会比较杂乱
建议增加分组功能

**Comment by gitxiaofeng** [comment]
功能内部开发中，完善后会开源出来

**Comment by gitxiaofeng** [comment]
已经增加文件夹管理方式
