### ISSUE TITLE
Docker镜像可以更新一版吗

### ISSUE THREAD

**Issue by weimo110** [didi/AgileTC#132]
快一年没有更新了，少很多功能

**Comment by gitxiaofeng** [comment]
> 快一年没有更新了，少很多功能

docker是外部开发同学帮忙维护的。

@yestodayHadRain 有空更新docker吗？

**Comment by yestodayHadRain** [comment]
> > 快一年没有更新了，少很多功能
> 
> docker是外部开发同学帮忙维护的。
> 
> @yestodayHadRain 有空更新docker吗？

不好意思,拖大家后退啦.刚刚已经对docker镜像进行了更新操作,和github的tag对应的v1.0.6版本.涉及改动的pr已提交
