### ISSUE TITLE
新增用例时关联需求，建议可以对接tapd或者jira需求接口，直接获取需求关联，不用手动填写

### ISSUE THREAD

**Issue by zhuangjd** [didi/AgileTC#14]
新增用例时关联需求，建议可以对接tapd或者jira需求接口，直接获取需求关联，不用手动填写

**Comment by gitxiaofeng** [comment]
近期可能还是以完善功能为主，对接外部的能力会往后面放。
本月会开源部分前端功能，有相关诉求可以二次开发的，欢迎共建

**Comment by gitxiaofeng** [comment]
前端功能已经开源，用户群里有同学二开的。可以联系交流
