### ISSUE TITLE
鼠标右键点击功能未做最顶层展示

### ISSUE THREAD

**Issue by jackferrous** [didi/AgileTC#16]
可以查出，右键功能有遮蔽
![image](https://user-images.githubusercontent.com/25580977/95671424-c7011100-0bc9-11eb-82a6-8883e85ac186.png)
正常是这样
![image](https://user-images.githubusercontent.com/25580977/95671431-daac7780-0bc9-11eb-94fc-2bfb4a380be0.png)

**Comment by chenhengjie123** [comment]
这个右键功能应该是 Kitymind 自带的那个。

kitymind 的作用范围只有可展示xmind内容的范围，即xmind内容会被遮挡的情况下，右键内容也一样会被遮挡。
