### ISSUE TITLE
编辑用例集时，关联需求变为空，原用例集新建是有关联需求的

### ISSUE THREAD

**Issue by zhuangjd** [didi/AgileTC#17]
编辑用例集时，关联需求变为空，原用例集新建是有关联需求的
![image](https://user-images.githubusercontent.com/22467118/95727518-d442fc00-0cac-11eb-8f96-e7d0e3c19bfa.png)
![image](https://user-images.githubusercontent.com/22467118/95727573-e6249f00-0cac-11eb-8407-ff70a5dc8dd8.png)

**Comment by gitxiaofeng** [comment]
bug已经修复
