### ISSUE TITLE
前端代码的开源有计划么

### ISSUE THREAD

**Issue by hgwz** [didi/AgileTC#22]
目前 import AgileTCEditor from '@didi/react-agiletc-editor';
基于 kitymindcore 的二次开发部分能先拿出来开源供大家二次开始使用么

**Comment by gitxiaofeng** [comment]
> 目前 import AgileTCEditor from '@didi/react-agiletc-editor';
> 基于 kitymindcore 的二次开发部分能先拿出来开源供大家二次开始使用么

会开源的。本月会部分开源，便于大家二次使用

**Comment by gitxiaofeng** [comment]
前端已经开源，可以支撑定制化开发了
