### ISSUE TITLE
建议增加xmind区域全屏展示功能

### ISSUE THREAD

**Issue by chenhengjie123** [didi/AgileTC#24]
用例评审时，一般需要分享到投影仪上。但在投影仪分辨率（720p左右）下，xmind展示的区域只有50%左右，导致投影效果不是很好。

如下图：
![image](https://user-images.githubusercontent.com/2800797/97078823-81106800-1621-11eb-939a-f2a65e6fabd8.png)

期望增加全屏展示的功能，把xmind区域（只包括上图中红框部分内容）放大到全屏

**Comment by gitxiaofeng** [comment]
> 用例评审时，一般需要分享到投影仪上。但在投影仪分辨率（720p左右）下，xmind展示的区域只有50%左右，导致投影效果不是很好。
> 
> 如下图：
> ![image](https://user-images.githubusercontent.com/2800797/97078823-81106800-1621-11eb-939a-f2a65e6fabd8.png)
> 
> 期望增加全屏展示的功能，把xmind区域（只包括上图中红框部分内容）放大到全屏

是的。这块后续会增加，功能完成后同步给你

**Comment by gitxiaofeng** [comment]
全屏功能已经增加
