### ISSUE TITLE
用例设计页面上半部分页面太大了

### ISSUE THREAD

**Issue by 18538570410** [didi/AgileTC#26]
建议用例设计页面上半部分页面放到左边，上面的内容实在是太过于占据屏幕，
其实仅仅是这样一个小问题，没有办法在测试部门推广开来。
![image](https://user-images.githubusercontent.com/56760997/98319961-de8eb680-201c-11eb-8969-c99aa84e4cc0.png)

**Comment by gitxiaofeng** [comment]
> 建议用例设计页面上半部分页面放到左边，上面的内容实在是太过于占据屏幕，
> 其实仅仅是这样一个小问题，没有办法在测试部门推广开来。
> ![image](https://user-images.githubusercontent.com/56760997/98319961-de8eb680-201c-11eb-8969-c99aa84e4cc0.png)

下周优化下这个问题

**Comment by gitxiaofeng** [comment]
已经优化
