### ISSUE TITLE
复制用例详情页的地址给其他人打开后自动跳转到了首页

### ISSUE THREAD

**Issue by sproutsbean** [didi/AgileTC#27]
想把当前测试用例分享给别人,但是别人打开后自动跳转到了用例首页导致别人不知道是要查看哪个用例

**Comment by gitxiaofeng** [comment]
> 想把当前测试用例分享给别人,但是别人打开后自动跳转到了用例首页导致别人不知道是要查看哪个用例

问题已经修复
