### ISSUE TITLE
可以提供Docker镜像吗

### ISSUE THREAD

**Issue by heyonghan** [didi/AgileTC#37]
项目发布，数据库配置仍然是很大的障碍，是否可以考虑在Dockerhub上发布一个镜像，可以快速部署了就

**Comment by gitxiaofeng** [comment]
> 项目发布，数据库配置仍然是很大的障碍，是否可以考虑在Dockerhub上发布一个镜像，可以快速部署了就

有的。参考 "AgileTC docker部署.md"
