### ISSUE TITLE
用户权限管理功能什么时候添加，另外什么时候提供用例版本回滚功能，我看case_backup表里面有保存记录啊。

### ISSUE THREAD

**Issue by Tester-1991** [didi/AgileTC#4]

**Comment by gitxiaofeng** [comment]
用户权限管理还得等等，近期需求实在排不开。功能上线了我们会在用户群中同步信息的。
版本管理暂时没做的，只是存在数据库中，用于网络异常，用例丢失时紧急恢复数据使用的。还没有做版本回滚功能的打算

**Comment by zhuangjd** [comment]
期望用户管理这部分功能可以优先排期，多人编辑用例或者新增用例或者删除用例，查不到对应人操作，都是统一user用户，确实不便于管理，

**Comment by xiaotangtang2014** [comment]
严重同意，如果能分辨出是谁在操作，就可以了，哪怕不权限控制就成，现在都是user，分不清，还不敢真正的用起来~~大神们加油~期待早日实现

**Comment by hellolocus** [comment]
请问大佬  用户权限管理有排期计划了吗？

**Comment by hellolocus** [comment]
用户群有么 发一下 多谢

**Comment by gitxiaofeng** [comment]
> 请问大佬 用户权限管理有排期计划了吗？

排期中了，已经初步确定方案了。预计1个月左右上线
