### ISSUE TITLE
期望可支持跨用例复制粘贴批量xmind节点

### ISSUE THREAD

**Issue by chenhengjie123** [didi/AgileTC#44]
应用场景：
1、刚引入平台的过渡期，有部分用例需要从历史的xmind文件用例中复制粘贴后进行调整。但发现本地xmind文件复制后，在平台上粘贴没反应
2、长期使用，某个新需求需要回归部分老需求的用例，想要把老需求用例里的部分节点复制粘贴过来，发现没反应

期望能支持这两个场景下的复制粘贴

PS：以前用百度原始 kityminder 这两个功能都是可以的。

**Comment by gitxiaofeng** [comment]
> 应用场景：
> 1、刚引入平台的过渡期，有部分用例需要从历史的xmind文件用例中复制粘贴后进行调整。但发现本地xmind文件复制后，在平台上粘贴没反应
> 2、长期使用，某个新需求需要回归部分老需求的用例，想要把老需求用例里的部分节点复制粘贴过来，发现没反应
> 
> 期望能支持这两个场景下的复制粘贴
> 
> PS：以前用百度原始 kityminder 这两个功能都是可以的。

前端已经修改，近期比较忙。发布后同步给你
