### ISSUE TITLE
react-agiletc-editor 这个组件会开源吗？

### ISSUE THREAD

**Issue by chinsyuu** [didi/AgileTC#56]
是否可以会开源？在二次开发中，修改这里的逻辑时，目前是无法修改的

**Comment by gitxiaofeng** [comment]
> 是否可以会开源？在二次开发中，修改这里的逻辑时，目前是无法修改的

会开源的。前端开发正在弄，开源时间可能会略晚一些。如果这期间有必须修改这个模块的地方，可以在用户群跟前端交流，看她是否可以将这块功能加进去，或者给我们提功能优化类的issue

**Comment by zhaozhiquan** [comment]
请问react-agiletc-editor组件开源时间有计划嘛？一些前端的问题没法修改耶。
