### ISSUE TITLE
关于脑图优先级

### ISSUE THREAD

**Issue by liangjingdev** [didi/AgileTC#57]
想问一下，关于百度脑图内置的优先级是如何改的呀？我替换了百度脑图原有的优先级图片，如图，加入了P0优先级：
![image](https://user-images.githubusercontent.com/25202438/105691302-07e22300-5f38-11eb-8197-d1909319f8d1.png)
但是点击P0优先级的图标，思维导图节点显示的却是原来的P1级别的图标。

**Comment by liangjingdev** [comment]
有人可以帮忙解答下吗

**Comment by gitxiaofeng** [comment]
> 想问一下，关于百度脑图内置的优先级是如何改的呀？我替换了百度脑图原有的优先级图片，如图，加入了P0优先级：
> ![image](https://user-images.githubusercontent.com/25202438/105691302-07e22300-5f38-11eb-8197-d1909319f8d1.png)
> 但是点击P0优先级的图标，思维导图节点显示的却是原来的P1级别的图标。

这个不太清楚啊。你在控制台看一下priority这个字段的值是不是符合预期呢，可能需要你调整下kityminder-editor的代码
