### ISSUE TITLE
这个没开源没法二次开发

### ISSUE THREAD

**Issue by wengxiaofeng** [didi/AgileTC#6]
import AgileTCEditor from '@didi/react-agiletc-editor';

**Comment by gitxiaofeng** [comment]
前端功能在内部试用中，还不成熟。等功能更加成熟一些会把前端这块的也开源出去

**Comment by gitxiaofeng** [comment]
已经开源，可以支持二次开发了

**Comment by Master-An** [comment]
> 开发

请问在哪儿可以看到这个组件的开源代码

**Comment by Master-An** [comment]
> 已经开源，可以支持二次开发了

请问在哪儿可以看到这个组件的开源代码
