### ISSUE TITLE
建议保存支持快捷键

### ISSUE THREAD

**Issue by chenhengjie123** [didi/AgileTC#7]
目前保存只能通过保存按钮。

mac 上通过 command+s ，会出现保存提示，但实际重新打开原来的内容已经消失，实际是没有保存成功的。

一般 xmind 编写会比较多用键盘，建议让保存快捷键真正起到保存作用。

**Comment by gitxiaofeng** [comment]
command+s这个是浏览器的快捷键，保存的是网页页面。
我们做了页面退出自动保存的功能，页面的保存按钮是兜底的，网络异常是备份用的。
做快捷键保存，可能也会是其他键，会产生学习成本。

**Comment by chenhengjie123** [comment]
现在实际上 command+s 已经被前端拦截了，也触发不了网页页面的保存。

按照上面的回复，是不是要考虑把这个前端拦截+保存成功（实际没有触发保存）去掉？

![image](https://user-images.githubusercontent.com/2800797/94410265-c0c26c00-01a9-11eb-846b-1d3eebe71fdf.png)

PS：对于这个用例编辑页面，浏览器保存页面是低频操作（甚至我没想到什么情况下需要这个操作，保存下来离线打开其实也不会能看到当时保存的用例内容），保存用例是高频操作。个人意见，不一定要牺牲高频操作来保持这个低频操作的快捷键。

**Comment by flyYoyo** [comment]
最近业务比较忙，这个保存快捷键的问题十一回来后修复。

**Comment by flyYoyo** [comment]
@chenhengjie123 最近业务比较忙，这个保存快捷键的问题十一回来后修复。

**Comment by chenhengjie123** [comment]
@flyYoyo 感谢

**Comment by gitxiaofeng** [comment]
> @flyYoyo 感谢

特性已经支持，有空可以check一下哈

**Comment by chenhengjie123** [comment]
> > @flyYoyo 感谢
> 
> 特性已经支持，有空可以check一下哈

已经用上了，感谢感谢！
