### ISSUE TITLE
根据优先级创建任务，报：服务器正忙

### ISSUE THREAD

**Issue by alongingz** [didi/AgileTC#73]
[http-nio-8094-exec-6][ERROR][com.xiaoju.framework.controller.RecordController.createRecord(RecordController.java:58)]:[新增record出错]入参=RecordAddReq(caseId=2212, creator=user, title=创建任务报错, chooseContent={"priority":["1"],"resource":[]}, description=, expectEndTime=1618329599999, expectStartTime=1618243200000, owner=), 原因=null

**Comment by gitxiaofeng** [comment]
> [http-nio-8094-exec-6][ERROR][com.xiaoju.framework.controller.RecordController.createRecord(RecordController.java:58)]:[新增record出错]入参=RecordAddReq(caseId=2212, creator=user, title=创建任务报错, chooseContent={"priority":["1"],"resource":[]}, description=, expectEndTime=1618329599999, expectStartTime=1618243200000, owner=), 原因=null

后端改版了，麻烦确认下问题是否还存在
